import React, { useMemo, useState } from 'react';
import { CheckCircle2, Search, XCircle } from 'lucide-react';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Input } from '../../components/ui/Input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/Table';
import { mockPayments } from '../../data/paymentData';
import type { Payment, PaymentStatus } from '../../types/payment';

const variant = (status: PaymentStatus) => status === 'Réussi' ? 'success' : status === 'Échoué' ? 'danger' : status === 'En attente' ? 'warning' : 'outline';
export function AdminPayments() {
  const [payments, setPayments] = useState(mockPayments);
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<'Tous' | PaymentStatus>('Tous');
  const filtered = useMemo(() => payments.filter(payment => (filter === 'Tous' || payment.status === filter) && `${payment.userName} ${payment.reference}`.toLowerCase().includes(search.toLowerCase())), [payments, filter, search]);
  const updateStatus = (id: number, status: PaymentStatus) => setPayments(current => current.map(payment => payment.id === id ? { ...payment, status, paidAt: status === 'Réussi' ? new Date().toISOString() : payment.paidAt } : payment));
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">Gestion des paiements</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Contrôlez et validez les transactions reçues.</p></div><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="flex flex-wrap gap-2">{(['Tous', 'En attente', 'Réussi', 'Échoué', 'Remboursé'] as const).map(status => <Button key={status} size="sm" variant={filter === status ? 'primary' : 'outline'} onClick={() => setFilter(status)}>{status}</Button>)}</div><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input className="pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Client ou référence…" /></div></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><Table><TableHeader><TableRow><TableHead>Référence</TableHead><TableHead>Client</TableHead><TableHead>Objet</TableHead><TableHead>Montant</TableHead><TableHead>Méthode</TableHead><TableHead>Statut</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{filtered.map(payment => <TableRow key={payment.id}><TableCell className="font-mono text-xs">{payment.reference}</TableCell><TableCell className="font-medium text-slate-900 dark:text-white">{payment.userName}</TableCell><TableCell>{payment.description}</TableCell><TableCell className="font-semibold">{payment.amount} {payment.currency}</TableCell><TableCell>{payment.method}</TableCell><TableCell><Badge variant={variant(payment.status)}>{payment.status}</Badge></TableCell><TableCell>{payment.status === 'En attente' && <div className="flex gap-1"><Button title="Valider" size="icon" variant="ghost" className="text-green-600" onClick={() => updateStatus(payment.id, 'Réussi')}><CheckCircle2 className="h-4 w-4" /></Button><Button title="Refuser" size="icon" variant="ghost" className="text-red-500" onClick={() => updateStatus(payment.id, 'Échoué')}><XCircle className="h-4 w-4" /></Button></div>}</TableCell></TableRow>)}{!filtered.length && <TableRow><TableCell colSpan={7} className="py-10 text-center text-slate-500">Aucun paiement trouvé.</TableCell></TableRow>}</TableBody></Table></div></div>;
}
